name = "NULP Linux Minecraft"
author = "Kaspiy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "268f622dadcf75ceb2f67ce4ae6f37aca9db16b87dd10d027a5e729485a40fa1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
