name = "NULP Linux Minecraft"
author = "Kaspiy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47eb3a0828a27c13972dfa7d92d6a7a178c118c17b95174875296fb5d3ed3409"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
